### ISSUE TITLE
why OpenFlow send multicast packet-in message.

### ISSUE THREAD

**Issue by chitsukhin** [mininet/openflow-tutorial#12]
![image](https://user-images.githubusercontent.com/51238327/72241224-a5f89900-3614-11ea-9efa-5966eeaf1583.png)
we use linear topology using this command.
**sudo mn --topo linear,3 --switch ovsk --controller remote -x --mac**
Why OpenFlow send multicast packet-in message (using this address 33:33:00:00:00:00:fb) continuously.

**Comment by lantz** [comment]
Please use the mailing list for questions like "how do I disable mDNS?"
