### ISSUE TITLE
Change to doc

### ISSUE THREAD

**Issue by kleenkanteen** [mininet/openflow-tutorial#15]
Page: https://github.com/mininet/openflow-tutorial/wiki/Set-up-Virtual-Machine

It says:  ` C:> putty.exe -X openflow@[Guest IP Here]`

It should say ` C:> putty.exe -X [user]@[Guest IP Here]`

as the user may be mininet

**Comment by lantz** [comment]
Please feel free to edit the page - it's a wiki after all. Thanks.
