### ISSUE TITLE
Bad instructions for starting a remote controller (?)

### ISSUE THREAD

**Issue by pturley0** [mininet/openflow-tutorial#6]
In the page [Learn Development Tools](https://github.com/mininet/openflow-tutorial/wiki/Learn-Development-Tools), the flow generally goes like this:

* Start up Mininet for use with a remote controller.
* Do some experiments and learn how it works without a controller.
* Start Wireshark.
* Start the remote controller.
* Look in Wireshark for OpenFow messages exchanged by the controller and the switch.

This doesn't work, because the _switch_ must reach out to the _controller_, and it can't do this if the controller is started _later_.

To make this work, you must:

* Shut down Mininet.
* Start the controller.
* Start Mininet again.
* Observe in Wireshark that the controller and the switch are communicating.

The goal of this issue is to accomplish one of the following:

1. Get the section "[Start Controller and view Startup messages in Wireshark](https://github.com/mininet/openflow-tutorial/wiki/Learn-Development-Tools#Start_Controller_and_view_Startup_messages_in_Wireshark)" changed to include the instructions shown immediately above.
1. Get an explanation of why my understanding is incorrect (which it very well may be).

**Comment by khursheedali38** [comment]
I also think the same should be followed in the page [Create a Learning Switch](https://github.com/mininet/openflow-tutorial/wiki/Create-a-Learning-Switch), as mentioned by @pturley0 the remote controller must be active before setting the topology up, because the `sudo mn` also points to the controller at the end of the network creation.

**Comment by zrjaa1** [comment]
Agree. Thanks for providing this!

**Comment by michaelcourcy** [comment]
I've changed the doc, stop and clean the topo, start the controller, recreate the topo.
